//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PumpKIN.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_TRAYICON                    101
#define IDD_PUMPKIN_DIALOG              102
#define IDS_FMT_BYTES                   102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_TFTP_ERROR_ACCESS           104
#define IDS_TFTP_ERROR_NOTFOUND         105
#define IDS_TFTP_ERROR_DIRFULL          106
#define IDD_PROPS_SERVER                106
#define IDS_TFTP_ERROR_SHARING          107
#define IDD_PROPS_NETWORK               107
#define IDS_TFTP_ERROR_DISKFULL         108
#define IDS_TFTP_ERROR_UNDEFINED        109
#define IDS_LOG_START                   110
#define IDS_LOG_LISTENRECEIVEERROR      111
#define IDS_LOG_LISTENACCEPTERROR       112
#define IDS_LOG_RRQSERVE                113
#define IDS_LOG_LISTENOPCODE            114
#define IDS_LOG_XFERUDPSEND             115
#define IDS_LOG_XFERRECEIVE             116
#define IDS_LOG_XFERSEND                117
#define IDS_LOG_XFERUDPRECEIVE          118
#define IDS_LOG_XFERSOURCETID           119
#define IDS_LOG_SENTTFTPERROR           120
#define IDS_LOG_GOTTFTPERROR            121
#define IDS_LOG_XFEROPCODE              122
#define IDS_LOG_XFERRRQFINISHED         123
#define IDS_TITLE_OPTIONS               124
#define IDS_LOG_WRQSERVE                125
#define IDS_TFTP_ERROR_FAILEDTORENAME   126
#define IDS_RENAME_TITLE                127
#define IDR_MAINFRAME                   128
#define IDS_LOG_TIMEDOUT                128
#define IDS_CONFIRMEXIT_TITLE           129
#define IDI_RRQ                         129
#define IDS_CONFIRMEXIT_TEXT            130
#define IDI_WRQ                         130
#define IDD_CONFIRM_RRQ                 131
#define IDS_LOG_XFERWRQFINISHED         131
#define IDD_CONFIRM_WRQ                 132
#define IDB_BACKGROUND                  132
#define IDS_LOG_XFERABORTED             132
#define IDS_TITLE_PUTREQUEST            133
#define IDS_TITLE_GETREQUEST            134
#define IDR_WAVE_RING                   135
#define IDS_TALKHEADING                 135
#define IDS_WTALKHEADING                135
#define IDR_WAVE_FINISHED               136
#define IDS_TITLE_BROWSEFILE            136
#define IDD_REQUEST                     137
#define IDS_LOG_RESOLVEFAILED           137
#define IDS_LOG_FAILEDLOCALFILE         138
#define IDD_PROPS_SOUNDS                138
#define IDS_LOG_FAILEDTOOPEN            139
#define IDM_POPUPS                      140
#define IDS_OTALXHEADING                140
#define IDS_REGISTRYKEY                 141
#define IDS_KLEVERNET_URL               142
#define IDR_WAVE_ABORTED                142
#define IDS_LOGTIMEFORMAT               143
#define IDS_DROPFILES_TITLE             144
#define IDS_NOMULTIPLEDROP_TEXT         145
#define IDI_BROWSE                      145
#define IDS_LOG_REQUESTING              146
#define IDS_LOG_SENDING                 147
#define IDS_WTALKAT                     148
#define IDS_OTALXAT                     149
#define IDI_PLAY                        149
#define IDS_TFTP_ERROR_TSIZE            150
#define IDD_PROPS_ACL                   150
#define IDS_TFTP_ERROR_BSIZE            151
#define IDS_TFTP_ERROR_TOUT             152
#define IDI_UP                          152
#define IDS_SELECT_TFTPROOT             153
#define IDI_DOWN                        153
#define IDS_FILTER_WAV                  154
#define IDI_REMOVE                      154
#define IDS_TITLE_WAV                   155
#define IDS_BOX_CANTBIND                156
#define IDS_NO_XFER_OP                  157
#define IDS_INVALID_IP                  158
#define IDS_INVALID_NETMASK             159
#define IDS_INVALID_RULE                160
#define IDS_LOG_LOGERROR                161
#define IDC_KLEVERNET                   1000
#define IDC_CONNECTIONS                 1001
#define IDC_LOG                         1003
#define IDC_GET                         1004
#define IDC_PUT                         1005
#define IDC_ABORT                       1006
#define IDC_EXIT                        1007
#define IDC_TFTPROOT                    1008
#define IDC_TFTPSUBDIRS                 1009
#define IDC_RRQ_GIVEALL                 1010
#define IDC_RRQ_ALWAYSCONFIRM           1011
#define IDC_RRQ_DENYALL                 1012
#define IDC_WRQ_TAKEALL                 1013
#define IDC_WRQ_PROMPTEXISTING          1014
#define IDC_WRQ_ALWAYSCONFIRM           1015
#define IDC_WRQ_DENYALL                 1016
#define IDC_PROMPTTIMEOUT               1017
#define IDC_LISTENPORT                  1018
#define IDC_LISTENSPIN                  1019
#define IDC_SPEAKPORT                   1020
#define IDC_SPEAKSPIN                   1021
#define IDC_MAXUDPSIZE                  1022
#define IDC_MAXUDPSPIN                  1023
#define IDC_TIMEOUT                     1024
#define IDC_TIMESPIN                    1025
#define IDC_OPTIONS                     1026
#define IDC_BLOCKSIZE                   1026
#define IDC_BSIZESPIN                   1027
#define IDC_HOST                        1028
#define IDC_FILE                        1029
#define IDC_RENAME                      1030
#define IDC_REMOTEFILE                  1030
#define IDC_RESUME                      1031
#define IDC_REFRESH                     1032
#define IDC_BROWSE                      1034
#define IDC_TALKS                       1035
#define IDC_LOCALFILE                   1036
#define IDC_TYPE                        1037
#define IDC_BSIZE                       1039
#define IDC_RING                        1041
#define IDC_RING_BROWSE                 1042
#define IDC_RING_PLAY                   1043
#define IDC_ACL_LIST                    1043
#define IDC_FINISHED                    1044
#define IDC_ACL_UP                      1044
#define IDC_FINISHED_BROWSE             1045
#define IDC_ACL_DOWN                    1045
#define IDC_FINISHED_PLAY               1046
#define IDC_ACL_REMOVE                  1046
#define IDC_ABORTED                     1047
#define IDC_ACL_ADDR                    1047
#define IDC_ABORTED_BROWSE              1048
#define IDC_ACL_RULE                    1048
#define IDC_ABORTED_PLAY                1049
#define IDC_ACL_NETMASK                 1049
#define IDC_ACL_ADD                     1050
#define IDC_ACL_XFER                    1051
#define IDC_ACL_REPLACE                 1052
#define IDC_LISTENING                   1052
#define IDC_LOGFILE                     1053
#define IDC_LOGFILE_BROWSE              1054
#define ID_TRAY_HELP                    32771
#define ID_TRAY_ABOUTPUMPKIN            32772
#define ID_TRAY_EXIT                    32773
#define ID_TRAY_SENDFILE                32774
#define ID_TRAY_FETCHFILE               32775
#define ID_TRAY_OPTIONS                 32776
#define ID_TRAY_SHOWPUMPKINWINDOW       32777
#define ID_TRAY_OPENFILESFOLDER         32778
#define ID_TRAY_LISTEN                  32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
